-- 코드를 작성해주세요
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GENERATION 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL 
    UNION ALL
    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, G.GENERATION 
FROM GEN G
WHERE NOT EXISTS(
    SELECT 1
    FROM ECOLI_DATA C
    WHERE C.PARENT_ID = G.ID
)
GROUP BY G.GENERATION
ORDER BY G.GENERATION; 